export type Provider = "aws" | "gcp";
export type Config = Record<string,string>;
export type Field = {key:string;label:string;help:string;options:[string,string][]};
export type Service = {title:string;aws:string;gcp:string;description:string;cost:number;fields:Field[]};
const field=(key:string,label:string,help:string,options:[string,string][]):Field=>({key,label,help,options});
const region=field("region","リージョン","リソースを置く地理的な場所。近さと障害範囲を考えます。",[["tokyo","東京"],["osaka","大阪"],["us","米国"]]);
const state=field("state","稼働状態","停止中は処理できません。ディスクなどの料金は残ります。",[["running","稼働"],["stopped","停止"]]);
const access=field("access","アクセス範囲","必要な相手だけにアクセスを許可します。",[["private","非公開 / 認証必須"],["public","インターネット全体"]]);
const network=field("network","ネットワーク","社内向けはプライベートネットワークを使います。",[["public","パブリック"],["private","プライベート"]]);
export const services:Record<string,Service>={
 vm:{title:"仮想サーバー",aws:"Amazon EC2",gcp:"Compute Engine",description:"アプリやゲームを動かすコンピューター。",cost:18,fields:[region,field("size","マシン構成","教材内の性能区分です。実際の型番・価格とは異なります。",[["small","小型 · 2 vCPU"],["large","大型 · 8 vCPU"],["gpu","GPU付き"]]),field("count","台数","台数を増やすと処理能力と費用が増えます。",[["1","1台"],["2","2台"],["4","4台"]]),network,field("port","許可する通信","通信経路のルールを簡略化しています。",[["none","許可なし"],["443","HTTPS · TCP 443"],["udp","ゲーム · UDP 7777"],["internal","社内ネットワークのみ"]]),state]},
 storage:{title:"ファイル保管",aws:"Amazon S3",gcp:"Cloud Storage",description:"画像、動画、バックアップをオブジェクトとして保管。",cost:5,fields:[region,access,field("versioning","バージョニング","上書き前の世代を保持して復元に備えます。",[["off","無効"],["on","有効"]]),field("tier","保存クラス","頻繁に使うものは標準、長期保管はアーカイブ。",[["standard","標準"],["archive","アーカイブ"]]),field("objects","サンプルデータ","外部送信せず、教材内のデータを置きます。",[["none","空"],["video","動画 1本"],["photos","写真 10枚"],["weather","天気CSV · 1,000行"]])]},
 cdn:{title:"配信キャッシュ",aws:"CloudFront",gcp:"Cloud CDN",description:"利用者に近い拠点からコンテンツを配信。",cost:8,fields:[field("origin","オリジン","配信元になるリソース。ここでは保管バケットを使います。",[["none","未接続"],["storage","ファイル保管"]]),field("cache","キャッシュ","同じデータを近くの拠点に一時保存します。",[["off","無効"],["on","有効"]]),field("tls","HTTPS","通信を暗号化します。実環境では証明書も必要です。",[["off","無効"],["on","有効"]])]},
 lb:{title:"負荷分散",aws:"Elastic Load Balancing",gcp:"Cloud Load Balancing",description:"複数のサーバーへ通信を振り分けます。",cost:10,fields:[field("target","バックエンド","通信を届けるサーバー群を登録します。",[["none","未登録"],["vm","仮想サーバー"]]),field("protocol","通信方式","用途に合う方式を選びます。UDPは対応するLBが必要です。",[["https","HTTPS"],["udp","UDP"]]),field("health","ヘルスチェック","停止したサーバーを振り分け先から外します。",[["off","無効"],["on","有効"]])]},
 db:{title:"データベース",aws:"Amazon RDS",gcp:"Cloud SQL",description:"注文や在庫を構造化して保存します。",cost:25,fields:[region,network,field("engine","エンジン","この教材のアプリはPostgreSQLを使用します。",[["mysql","MySQL"],["postgres","PostgreSQL"]]),field("backup","自動バックアップ","削除や障害に備えます。",[["off","無効"],["on","有効"]]),field("ha","高可用性","別ゾーンの予備に切り替えられる構成。",[["off","単一ゾーン"],["on","複数ゾーン"]])]},
 queue:{title:"メッセージキュー",aws:"Amazon SQS",gcp:"Pub/Sub",description:"仕事をためて、処理する側へ渡す。両サービスの配信モデルは異なります。",cost:3,fields:[field("consumer","処理先","受け取るワーカーを接続します。",[["none","未接続"],["vm","仮想サーバー"],["function","イベント処理"]]),field("retry","再試行","一時的に失敗した仕事を再び処理します。",[["off","無効"],["on","有効"]]),field("dlq","失敗メッセージの退避","繰り返し失敗する仕事を別の場所へ退避します。",[["off","無効"],["on","有効"]])]},
 function:{title:"イベント処理",aws:"AWS Lambda",gcp:"Cloud Run functions",description:"リクエストやイベントを受けて短い処理を実行。",cost:4,fields:[field("trigger","トリガー","何が起きたら処理を開始するか。",[["none","未設定"],["http","HTTPリクエスト"],["queue","キュー受信"],["schedule","定期実行"]]),field("role","実行権限","処理に必要な範囲だけ許可します。",[["none","権限なし"],["read","データ読取"],["notify","通知送信"],["admin","全操作"]]),field("action","処理内容","教材内の処理を選びます。",[["none","未設定"],["payment","決済サンドボックス"],["alert","異常を通知"],["aggregate","データ集計"]])]},
 iam:{title:"権限管理",aws:"IAM",gcp:"IAM",description:"誰が何をできるかを決める。ポリシー方式はサービスごとに異なります。",cost:0,fields:[field("principal","利用者","権限を与える対象。",[["everyone","全員"],["team","チーム"],["service","サービス用ID"]]),field("permission","許可する操作","最小限の権限を選びます。",[["none","なし"],["read","読取のみ"],["admin","管理者"]])]},
 analytics:{title:"データ分析",aws:"Amazon Athena",gcp:"BigQuery",description:"データをSQLで集計する。保存方式や課金方式は異なります。",cost:12,fields:[field("source","入力データ","分析元を接続します。",[["none","未接続"],["storage","ファイル保管"]]),field("query","クエリ","天気サンプルの気温を集計します。",[["all","SELECT *"],["avg","SELECT AVG(temperature)"]]),field("partition","読み取り範囲","必要な日付だけを読むことでスキャン量を減らします。",[["all","全期間"],["day","1日だけ"]])]},
 sensor:{title:"デバイス受信",aws:"AWS IoT Core",gcp:"MQTT broker on Compute Engine",description:"工場のセンサーを受信。Google側はVM上のMQTT構成例で、直接の同等製品ではありません。",cost:6,fields:[field("auth","デバイス認証","登録したデバイスだけが送信できるようにします。",[["off","なし"],["on","認証あり"]]),field("topic","トピック","メッセージを分ける宛先。",[["all","すべて"],["factory","factory/temperature"]]),field("route","転送先","異常判定にメッセージを渡します。",[["none","未設定"],["queue","メッセージキュー"]])]},
 vpn:{title:"社内接続",aws:"AWS Site-to-Site VPN",gcp:"Cloud VPN",description:"オフィスとクラウドを暗号化した経路で接続。",cost:15,fields:[region,field("tunnel","VPNトンネル","この教材では接続済みを選ぶことで確立を模擬します。",[["off","未接続"],["on","接続済み"]]),field("route","ルート","社内宛ての通信をVPNへ送ります。",[["none","未設定"],["private","10.0.0.0/16"]])]},
 replica:{title:"別地域の予備",aws:"EC2 + backup restore",gcp:"Compute Engine + backup restore",description:"別地域へ復元した予備サーバー。バックアップは事前取得済みとします。",cost:18,fields:[region,field("sync","復元ポイント","障害前のバックアップから復元します。",[["none","未復元"],["ready","復元済み"]]),state]},
 dns:{title:"接続先切替",aws:"Route 53",gcp:"Cloud DNS",description:"名前から接続先を引くDNS。ここでは手動切替を模擬します。",cost:1,fields:[field("target","接続先","利用者をどのサーバーへ案内するか。",[["vm","メイン"],["replica","別地域の予備"]]),field("ttl","TTL","DNS情報をキャッシュする時間。実際の反映には時間差があります。",[["3600","3,600秒"],["60","60秒"]])]},
 budget:{title:"予算通知",aws:"AWS Budgets",gcp:"Cloud Billing budgets",description:"費用のしきい値で通知。予算設定だけではリソースは停止しません。",cost:0,fields:[field("limit","教材の月額予算","実料金ではなく教材内の比較単位です。",[["200","200"],["60","60"],["30","30"]]),field("notify","通知","超過を知らせます。自動停止ではありません。",[["off","なし"],["on","有効"]])]},
};
export const defaults=(service:string):Config=>Object.fromEntries(services[service].fields.map(f=>[f.key,f.options[0][0]]));
export type Choice={label:string;config:Config;explanation:string};
export type Task={title:string;brief:string;service:string;require:Config;choices:Choice[];lesson:string;event?:string};
export type Mission={id:string;title:string;category:string;summary:string;path:string[];tasks:Task[]};
const task=(title:string,brief:string,service:string,require:Config,good:string,bad:[string,Config,string][],lesson:string,event?:string):Task=>{
 const choices=[...bad.map(([label,config,explanation])=>({label,config,explanation})),{label:good,config:require,explanation:lesson}];
 const offset=Array.from(title).reduce((n,c)=>n+c.charCodeAt(0),0)%choices.length;
 return {title,brief,service,require,choices:[...choices.slice(offset),...choices.slice(0,offset)],lesson,event};
};
export const missions:Mission[]=[
 {id:"web",title:"Webサイト公開",category:"入門",summary:"サーバーを作り、アクセス増加に備える。",path:["vm","lb"],tasks:[
 task("HTTPSで公開","東京に1台のサーバーを用意。外部からHTTPSでアクセスできるようにしてください。","vm",{region:"tokyo",count:"1",network:"public",port:"443",state:"running"},"東京のサーバーでHTTPSを許可",[["通信をすべて閉じる",{port:"none"},"外部からのリクエストが届きません。"],["内部専用にする",{network:"private"},"社内向けの構成では公開できません。"]],"サーバーを作るだけでなく、通信ルールも必要です。"),
 task("サーバーを増やす","アクセスが急増。稼働するサーバーを2台に増やしてください。","vm",{count:"2"},"2台に増やす",[["1台のまま",{count:"1"},"この教材の負荷は1台の処理能力を超えています。"],["サーバーを止める",{state:"stopped"},"停止すると処理できません。"]],"台数を増やすことがスケールアウトです。","アクセスが3倍になりました。"),
 task("入口で振り分ける","仮想サーバーをバックエンドに登録し、HTTPSとヘルスチェックを設定してください。","lb",{target:"vm",protocol:"https",health:"on"},"HTTPSで2台へ分散する",[["転送先を未登録にする",{target:"none"},"入口があっても転送先がありません。"],["UDPで転送する",{target:"vm",protocol:"udp"},"WebサイトのHTTPS通信とは方式が違います。"]],"LBが通信を分け、ヘルスチェックが正常なサーバーを見つけます。")]},
 {id:"video",title:"動画配信",category:"配信",summary:"動画を保管し、世界中へ速く届ける。",path:["storage","cdn"],tasks:[
 task("動画を保管","東京の標準クラスへサンプル動画を保存。保管元は非公開にしてください。","storage",{region:"tokyo",tier:"standard",objects:"video",access:"private"},"非公開の保管庫に動画を置く",[["空の保管庫だけ作る",{objects:"none"},"配信する動画がありません。"],["保管庫を全体公開",{objects:"video",access:"public"},"今回は配信入口にアクセスを集約する設計です。"]],"保管元を非公開にし、配信サービスに読取を許可する構成です。接続権限はこの教材では模擬します。"),
 task("配信元をつなぐ","配信キャッシュのオリジンをファイル保管に設定し、HTTPSを有効にしてください。","cdn",{origin:"storage",tls:"on"},"保管庫をHTTPS配信へつなぐ",[["配信元を設定しない",{origin:"none"},"動画を取りに行く先がありません。"],["暗号化せず配信",{origin:"storage",tls:"off"},"通信が暗号化されていません。"]],"オリジンは、CDNがコンテンツを取得する元の場所です。"),
 task("遠い利用者にも速く","キャッシュを有効にし、同じ動画を毎回保管元から取り寄せないようにしてください。","cdn",{cache:"on"},"近くの拠点にキャッシュ",[["キャッシュを無効",{cache:"off"},"同じ動画でもオリジンへのアクセスが続きます。"],["配信元を切断",{origin:"none"},"初めての動画を取得できません。"]],"CDNはよく使う内容を近くの拠点に保持します。","海外からの再生が増え、読み込みが遅くなりました。")]},
 {id:"game",title:"オンラインゲーム",category:"計算",summary:"UDP通信と同時接続の増加を扱う。",path:["vm","lb"],tasks:[
 task("ゲームサーバー起動","東京に稼働中のサーバーを1台。パブリックでUDP 7777を許可してください。","vm",{region:"tokyo",count:"1",network:"public",port:"udp",state:"running"},"UDP 7777で受け付ける",[["HTTPSだけ許可",{port:"443"},"今回のゲームはUDPを使います。"],["通信を閉じる",{port:"none"},"プレイヤーが接続できません。"]],"ゲームではWebとは異なる通信方式を使うことがあります。"),
 task("満員に対応","イベントで満員です。サーバーを4台にしてください。","vm",{count:"4"},"4台に増設",[["1台を使い続ける",{count:"1"},"今回の接続数をさばけません。"],["2台だけ用意",{count:"2"},"このシナリオでは4台分の能力が必要です。"]],"台数は需要に合わせます。実際はマッチメイクや状態管理も必要です。","接続が4倍に増えました。"),
 task("UDPの負荷分散","バックエンドを仮想サーバー、方式をUDPにしてヘルスチェックを有効に。","lb",{target:"vm",protocol:"udp",health:"on"},"UDP対応のLBを構成",[["HTTPSのLBにする",{target:"vm",protocol:"https"},"UDPのゲーム通信をこの設定では扱えません。"],["ヘルスチェックなし",{target:"vm",protocol:"udp",health:"off"},"故障した転送先を除外できません。"]],"AWSではNLBなど、UDP対応の負荷分散を選びます。")]},
 {id:"shop",title:"ネットショップ",category:"アプリ",summary:"注文の保存、決済処理、DBの障害対策。",path:["function","db"],tasks:[
 task("注文・在庫を保存","東京のプライベートDBをPostgreSQLで作成し、自動バックアップを有効に。","db",{region:"tokyo",network:"private",engine:"postgres",backup:"on"},"非公開DBをバックアップ付きで作る",[["DBをインターネットへ公開",{network:"public"},"アプリからだけアクセスする設計です。"],["バックアップを無効",{network:"private",backup:"off"},"誤削除から復元する備えが不足します。"]],"DBはアプリの裏側に置き、バックアップを取ります。"),
 task("テスト決済を受け付ける","HTTPトリガー、決済サンドボックス処理を設定。実行権限はデータ読取に。","function",{trigger:"http",action:"payment",role:"read"},"HTTPでテスト決済を実行",[["トリガー未設定",{trigger:"none"},"リクエストが処理を起動できません。"],["すべての権限を付与",{trigger:"http",action:"payment",role:"admin"},"この処理に管理者権限は必要ありません。"]],"外部決済との連携を模擬します。実決済・DBの注文処理・秘密情報の管理は実行しません。"),
 task("DB停止に備える","DBを複数ゾーン構成へ変更してください。","db",{ha:"on"},"別ゾーンにも予備を用意",[["単一ゾーンのまま",{ha:"off"},"ゾーン障害時に待機系へ切り替えられません。"],["バックアップを削る",{backup:"off"},"可用性とバックアップは別の役割です。"]],"高可用性は継続運転、バックアップは過去のデータの復元に役立ちます。","DBのあるゾーンで障害の予告です。")]},
 {id:"files",title:"写真・ファイル共有",category:"保存",summary:"共有範囲と権限、上書きからの復元。",path:["iam","storage"],tasks:[
 task("写真をアップロード","標準クラスの非公開バケットに写真10枚を置いてください。","storage",{objects:"photos",access:"private",tier:"standard"},"非公開で写真を保存",[["全体に公開する",{objects:"photos",access:"public"},"今回の写真はチーム専用です。"],["何も保存しない",{objects:"none"},"共有する写真がありません。"]],"非公開から始め、必要な相手にアクセス権を与えます。"),
 task("チームへ共有","利用者をチーム、許可を読取のみにしてください。","iam",{principal:"team",permission:"read"},"チームに閲覧だけ許可",[["全員に閲覧許可",{principal:"everyone",permission:"read"},"チーム外にも見えてしまいます。"],["チームを管理者に",{principal:"team",permission:"admin"},"閲覧のために削除や権限変更まで許可する必要はありません。"]],"閲覧と管理は違う権限です。対象リソースへの紐付けは教材内で模擬します。"),
 task("上書きに備える","保管庫のバージョニングを有効にしてください。","storage",{versioning:"on"},"今後の変更を世代保存",[["世代を保存しない",{versioning:"off"},"古い内容が失われる可能性があります。"],["アーカイブへ移動する",{tier:"archive"},"保存クラスの変更だけでは世代は残りません。"]],"有効化した後の変更を世代として保持します。すでに失われたデータが戻るわけではありません。","同じ名前の写真を上書きする作業が始まります。")]},
 {id:"ai",title:"AI画像生成",category:"計算",summary:"GPUワーカーと順番待ち、失敗の退避。",path:["queue","vm"],tasks:[
 task("GPUワーカーを用意","東京でGPU付きサーバーを1台稼働させてください。","vm",{size:"gpu",count:"1",region:"tokyo",state:"running"},"GPU付きサーバーを起動",[["小型CPUで処理",{size:"small"},"このモデルの教材条件はGPU必須です。"],["GPUを停止状態に",{size:"gpu",state:"stopped"},"停止中は仕事を処理できません。"]],"画像生成などはGPUが得意な並列計算を使います。実画像の生成は模擬です。"),
 task("仕事を並べる","キューの処理先を仮想サーバーに設定し、再試行を有効に。","queue",{consumer:"vm",retry:"on"},"キューからGPUへ渡す",[["処理先を空にする",{consumer:"none"},"仕事が待ち続けます。"],["失敗したら諦める",{consumer:"vm",retry:"off"},"一時的な失敗も取りこぼします。"]],"受付と処理を分けることで、混雑時も仕事を順番に処理できます。"),
 task("壊れた仕事を退避","失敗メッセージの退避を有効にしてください。","queue",{dlq:"on"},"繰り返し失敗する仕事を退避",[["再試行だけ繰り返す",{dlq:"off"},"原因が直らない仕事が繰り返されます。"],["ワーカーを切断",{consumer:"none"},"正常な仕事も進まなくなります。"]],"デッドレターキューは失敗した仕事を調査するための退避先です。","不正な入力の仕事が何度も失敗しています。")]},
 {id:"weather",title:"天気データ分析",category:"分析",summary:"CSVから平均を求め、読み取り量を抑える。",path:["storage","analytics"],tasks:[
 task("観測データを集める","標準クラスの非公開保管庫へ天気CSVを置いてください。","storage",{objects:"weather",tier:"standard",access:"private"},"天気CSVを保管",[["写真を置く",{objects:"photos"},"分析したい気温データではありません。"],["空の保管庫を用意",{objects:"none"},"集計対象がありません。"]],"収集と分析を分けると、同じデータを再利用できます。"),
 task("平均気温を集計","入力をファイル保管にし、AVG(temperature)のクエリを選んでください。","analytics",{source:"storage",query:"avg"},"平均気温を計算",[["全行を表示する",{source:"storage",query:"all"},"SELECT * は平均値を集計しません。"],["入力を未接続に",{source:"none"},"読み取る対象がありません。"]],"SQLの集計関数で、多数の行から必要な数字を得ます。"),
 task("スキャン量を減らす","読み取り範囲を1日だけにしてください。","analytics",{partition:"day"},"必要な日付だけ読む",[["全期間を毎回読む",{partition:"all"},"不要な日付までスキャンしています。"],["集計をやめる",{query:"all"},"取得量を抑えても平均は得られません。"]],"日付で区切ったデータから必要な範囲を読むと、処理量を抑えられます。","データが1年分になり、処理量が増えました。")]},
 {id:"factory",title:"工場の異常検知",category:"IoT",summary:"センサー受信から非同期の通知まで。",path:["sensor","queue","function"],tasks:[
 task("デバイスを認証","デバイス認証を有効にし、factory/temperatureトピックを選び、キューへ転送。","sensor",{auth:"on",topic:"factory",route:"queue"},"認証した温度センサーを接続",[["認証なしで受信",{auth:"off"},"不明な送信元が値を送れる構成です。"],["転送しない",{auth:"on",route:"none"},"受信した温度が後続処理へ届きません。"]],"Google側はVM上のMQTTブローカーを使う構成例です。旧Cloud IoT Coreの再現ではありません。"),
 task("受信と処理を分離","キューの処理先をイベント処理にして、再試行を有効に。","queue",{consumer:"function",retry:"on"},"キューから判定処理へ渡す",[["処理先なし",{consumer:"none"},"メッセージが滞留します。"],["再試行なし",{consumer:"function",retry:"off"},"一時的な処理失敗に備えられません。"]],"キューがあると、短時間に届いた大量の値を後から処理できます。"),
 task("異常温度を通知","キュー受信で異常通知を実行し、通知送信の権限を設定してください。","function",{trigger:"queue",action:"alert",role:"notify"},"80℃超のサンプルを通知",[["通知の権限なし",{trigger:"queue",action:"alert",role:"none"},"通知を送信する権限がありません。"],["HTTPで待機",{trigger:"http",action:"alert",role:"notify"},"キューのメッセージで起動しません。"]],"この教材では85℃のサンプルを80℃のしきい値と比較し、通知を模擬します。","温度センサーが85℃を送信しました。")]},
 {id:"office",title:"社内システム",category:"ネットワーク",summary:"VPN・プライベート接続・社員の権限。",path:["vpn","vm","iam"],tasks:[
 task("内部専用サーバー","東京のプライベートサーバーを起動し、通信は社内ネットワークのみに。","vm",{region:"tokyo",network:"private",port:"internal",state:"running"},"社内ネットワークだけ許可",[["外部公開する",{network:"public",port:"443"},"社外から直接接続する構成になっています。"],["全通信を閉じる",{network:"private",port:"none"},"社員からの通信も届きません。"]],"プライベートなネットワークは、インターネットへの直接公開を避けます。"),
 task("オフィスから接続","東京のVPNを接続済みにし、10.0.0.0/16のルートを設定。","vpn",{region:"tokyo",tunnel:"on",route:"private"},"VPNと社内宛ルートを設定",[["VPNだけ接続",{tunnel:"on",route:"none"},"通信を送る経路がありません。"],["トンネルを切断",{tunnel:"off"},"クラウドまでの経路がつながりません。"]],"VPN接続と、どの通信をそこへ送るかというルートの両方が必要です。"),
 task("社員の閲覧権限","利用者をチーム、許可を読取のみに。","iam",{principal:"team",permission:"read"},"社員へ読取権限を付ける",[["全員を許可",{principal:"everyone",permission:"read"},"社員以外にも権限を与えています。"],["権限を付けない",{principal:"team",permission:"none"},"ネットワークが届いても認証後の操作が拒否されます。"]],"ネットワーク接続と、アプリを使う権限は別々の制御です。")]},
 {id:"disaster",title:"災害からの復旧",category:"信頼性",summary:"別地域へ復元し、利用者の接続先を切り替える。",path:["vm","replica","dns"],tasks:[
 task("通常運転","東京に稼働中のパブリックサーバーを1台。HTTPSを許可してください。","vm",{region:"tokyo",state:"running",count:"1",network:"public",port:"443"},"東京で通常運転",[["停止状態にする",{state:"stopped"},"通常のサービスを開始できません。"],["通信を閉じる",{port:"none"},"利用者がアクセスできません。"]],"今回は別地域にも保管済みのバックアップがある前提です。"),
 task("大阪へ復元","大阪の予備サーバーを復元済み・稼働状態にしてください。","replica",{region:"osaka",sync:"ready",state:"running"},"大阪でバックアップを復元",[["東京にも予備を作る",{region:"tokyo",sync:"ready"},"同じ地域の障害に巻き込まれます。"],["未復元のまま起動",{region:"osaka",sync:"none"},"起動してもアプリのデータがありません。"]],"別地域に復元すると、地域全体の障害に備えられます。"),
 task("利用者を予備へ誘導","DNSの接続先を別地域の予備にし、TTLを60秒へ。","dns",{target:"replica",ttl:"60"},"DNSを大阪の予備へ切り替え",[["メインへ案内を続ける",{target:"vm"},"利用者が障害中の東京へ向かいます。"],["キャッシュを1時間に",{target:"replica",ttl:"3600"},"切替前の情報が長く残ります。"]],"実際のDNS切替は即時ではなく、以前のTTLなどに影響されます。","東京リージョンが停止しました。")]},
 {id:"cost",title:"クラウド料金削減",category:"コスト",summary:"使いすぎを見つけ、性能を残して費用を下げる。",path:["vm","storage","budget"],tasks:[
 task("過剰な構成を適正化","教材の開始構成は大型4台。小型1台へ変更し、稼働は維持してください。","vm",{size:"small",count:"1",state:"running"},"小型1台へ縮小",[["大型4台を維持",{size:"large",count:"4"},"この用途では余剰な能力です。"],["すべて停止",{state:"stopped"},"費用を下げても必要なサービスが止まります。"]],"性能の利用状況を見て構成を小さくするのがライトサイジングです。"),
 task("長期保管を安く","保管クラスをアーカイブへ。写真データと非公開設定を維持してください。","storage",{tier:"archive",objects:"photos",access:"private"},"古い写真をアーカイブへ",[["標準で保管を続ける",{tier:"standard"},"ほぼ読まないデータには割高な場合があります。"],["データを消す",{objects:"none"},"保存する要件を満たしません。"]],"アーカイブには読出し料金や待ち時間、最低保存期間などの条件があります。"),
 task("増額を見逃さない","教材の予算を30にし、通知を有効にしてください。","budget",{limit:"30",notify:"on"},"予算30で通知を設定",[["通知しない",{limit:"30",notify:"off"},"設定しても知らせが届きません。"],["予算を200にする",{limit:"200",notify:"on"},"今回の目標30を超えても通知されません。"]],"予算通知は自動停止ではありません。現在の教材費用も確認しましょう。")]},
];
export type Resource={name:string;config:Config};
export type Session={step:number;resources:Record<string,Resource>;passed:boolean;logs:string[];completed:boolean};
export function initial(m:Mission):Session{return{step:0,resources:m.id==="cost"?{vm:{name:"overprovisioned",config:{...defaults("vm"),size:"large",count:"4"}},storage:{name:"archive-photos",config:{...defaults("storage"),objects:"photos"}}}:{},passed:false,completed:false,logs:[]};}
export function requirements(m:Mission,step:number){const all:Record<string,Config>={};m.tasks.slice(0,step+1).forEach(t=>{all[t.service]={...all[t.service],...t.require}});if(m.id==="disaster"&&step===2)all.vm.state="stopped";return all;}
export function advance(m:Mission,s:Session):Session{const next={...s,step:Math.min(s.step+1,m.tasks.length-1),passed:false};if(m.id==="disaster"&&next.step===2&&next.resources.vm)next.resources={...next.resources,vm:{...next.resources.vm,config:{...next.resources.vm.config,state:"stopped"}}};return next;}
export function validate(m:Mission,s:Session){const expected=requirements(m,s.step);const errors:string[]=[];Object.entries(expected).forEach(([id,conf])=>{const resource=s.resources[id];if(!resource){errors.push(services[id].title+"がありません。");return;}Object.entries(conf).forEach(([key,value])=>{if(resource.config[key]!==value){const f=services[id].fields.find(x=>x.key===key)!;errors.push(services[id].title+"：「"+f.label+"」を「"+f.options.find(o=>o[0]===value)?.[1]+"」に設定してください。");}})});return errors;}
export function costOf(resources:Session["resources"]){return Object.entries(resources).reduce((sum,[id,r])=>{let c=services[id].cost;if(id==="vm")c*=Number(r.config.count||1)*(r.config.size==="large"?4:r.config.size==="gpu"?12:1);if(r.config.state==="stopped")c*=.15;if(id==="storage"&&r.config.tier==="archive")c*=.2;if(id==="db"&&r.config.ha==="on")c*=2;return sum+c;},0);}
export function applyConfig(s:Session,id:string,name:string,config:Config):Session{return{...s,passed:false,completed:false,resources:{...s.resources,[id]:{name,config:{...defaults(id),...config}}},logs:[services[id].title+"の設定を保存しました。",...s.logs].slice(0,12)};}
