"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, Cloud, Database, Globe2, HardDrive, RotateCcw, Server, ShieldCheck, Zap } from "lucide-react";
type Provider = "aws" | "gcp";
const names={aws:{server:"EC2",storage:"S3",database:"RDS",balancer:"ELB"},gcp:{server:"Compute Engine",storage:"Cloud Storage",database:"Cloud SQL",balancer:"Cloud Load Balancing"}};
const steps=[{title:"Webサーバーを作る",body:"まず、サイトを動かすコンピューターを用意します。",action:"サーバーを追加"},{title:"データベースをつなぐ",body:"予約情報を安全に保存する場所を追加します。",action:"データベースを追加"},{title:"アクセス急増！",body:"お店がSNSで話題に。サーバー1台では限界です。",action:"もう1台追加"},{title:"負荷を分ける",body:"2台のサーバーへアクセスを振り分けましょう。",action:"ロードバランサーを追加"}];
export default function Home(){
 const [provider,setProvider]=useState<Provider>("aws"); const [step,setStep]=useState(0); const done=step>=steps.length; const serverCount=step>=3?2:step>=1?1:0; const hasDb=step>=2; const hasLb=done; const load=done?38:step===3?94:step>=1?32:0; const cost=useMemo(()=>serverCount*9+(hasDb?12:0)+(hasLb?4:0),[serverCount,hasDb,hasLb]); const current=steps[Math.min(step,steps.length-1)];
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:"advance_cloud_mission",title:"次の構築操作を実行",description:"現在のCloud Labミッションで次に必要な構築操作を1つ実行し、画面を更新します。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{setStep(s=>Math.min(s+1,steps.length));return{status:"advanced"}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 return <main className="min-h-screen bg-[#07101f] text-slate-100">
  <header className="border-b border-white/10 bg-[#091426]/95"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-2.5 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-400 text-[#07101f]"><Cloud size={21}/></span>Cloud Lab</div><div className="flex rounded-xl border border-white/10 bg-white/5 p-1" aria-label="クラウドを選択"><button onClick={()=>setProvider("aws")} className={`rounded-lg px-3 py-2 text-sm font-bold ${provider==="aws"?"bg-[#ff9900] text-[#111827]":"text-slate-400"}`}>AWS</button><button onClick={()=>setProvider("gcp")} className={`rounded-lg px-3 py-2 text-sm font-bold ${provider==="gcp"?"bg-blue-500 text-white":"text-slate-400"}`}>Google</button></div></div></header>
  <div className="mx-auto grid max-w-6xl gap-4 px-4 py-4 sm:px-6 lg:grid-cols-[310px_1fr] lg:py-6">
   <section className="rounded-2xl border border-white/10 bg-[#0d1a2e] p-5 shadow-2xl shadow-black/20"><div className="mb-4 flex items-center justify-between"><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs font-bold text-cyan-300">MISSION 01</span><span className="text-sm text-slate-400">{Math.min(step+1,4)} / 4</span></div>
   {done?<div><div className="mb-4 grid h-12 w-12 place-items-center rounded-full bg-emerald-400 text-[#07101f]"><Check size={26}/></div><h1 className="text-2xl font-bold">公開成功！</h1><p className="mt-2 leading-relaxed text-slate-300">アクセスが増えても落ちにくいWebサイトが完成しました。</p><div className="mt-5 rounded-xl bg-emerald-400/10 p-4 text-sm text-emerald-200"><b>覚えたこと</b><br/>サーバーを増やし、入口で振り分けることを「スケールアウト」と呼びます。</div><button onClick={()=>setStep(0)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-white/15 py-3 font-bold"><RotateCcw size={17}/>もう一度</button></div>:<div><h1 className="text-2xl font-bold leading-tight">{current.title}</h1><p className="mt-2 min-h-14 leading-relaxed text-slate-300">{current.body}</p>{step===2&&<div className="mt-3 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm font-bold text-red-200">負荷 94% — このままでは停止します</div>}<button onClick={()=>setStep(step+1)} className="mt-5 flex w-full items-center justify-between rounded-xl bg-cyan-400 px-4 py-3.5 font-bold text-[#07101f] active:scale-[.98]">{current.action}<ChevronRight size={20}/></button><p className="mt-3 text-center text-xs text-slate-500">失敗しても料金はかかりません</p></div>}</section>
   <section className="min-w-0 rounded-2xl border border-white/10 bg-[#0a1628] p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">あなたのクラウド</h2><p className="text-sm text-slate-400">東京リージョン</p></div><div className="flex gap-2 text-xs sm:text-sm"><Metric icon={<Zap size={15}/>} label="負荷" value={`${load}%`} alert={load>80}/><Metric icon={<ShieldCheck size={15}/>} label="安全" value={serverCount?"80%":"—"}/><Metric label="月額" value={`$${cost}`}/></div></div>
   <div className="relative min-h-[370px] overflow-hidden rounded-2xl border border-white/10 bg-[#07101f] p-4 sm:p-7"><div className="absolute inset-0 grid-bg opacity-30"/><div className="relative flex min-h-[315px] flex-col items-center justify-center gap-5"><Node icon={<Globe2/>} title="Internet" tone="cyan"/><Connector/>{hasLb&&<><Node icon={<Zap/>} title={names[provider].balancer} subtitle="アクセスを振り分ける" tone="violet"/><Connector/></>}{serverCount===0?<div className="rounded-xl border border-dashed border-slate-600 px-6 py-5 text-sm text-slate-500">サーバーをここに追加</div>:<div className={`grid gap-3 ${serverCount===2?"grid-cols-2":"grid-cols-1"}`}>{Array.from({length:serverCount}).map((_,i)=><Node key={i} icon={<Server/>} title={`${names[provider].server} ${i+1}`} subtitle="仮想サーバー" tone="blue"/>)}</div>}{hasDb&&<><Connector/><Node icon={<Database/>} title={names[provider].database} subtitle="データベース" tone="green"/></>}</div></div>
   <div className="mt-4 flex gap-3 overflow-x-auto pb-1"><Concept icon={<Server/>} concept="仮想サーバー" service={names[provider].server} active={serverCount>0}/><Concept icon={<Database/>} concept="データベース" service={names[provider].database} active={hasDb}/><Concept icon={<HardDrive/>} concept="ファイル保存" service={names[provider].storage}/></div></section>
  </div>
 </main>;
}
function Metric({icon,label,value,alert=false}:{icon?:React.ReactNode;label:string;value:string;alert?:boolean}){return <div className={`rounded-lg border px-2.5 py-2 ${alert?"border-red-400/40 bg-red-400/10 text-red-200":"border-white/10 bg-white/5"}`}><div className="flex items-center gap-1 text-[11px] text-slate-400">{icon}{label}</div><b>{value}</b></div>}
function Node({icon,title,subtitle,tone}:{icon:React.ReactNode;title:string;subtitle?:string;tone:"cyan"|"blue"|"green"|"violet"}){const colors={cyan:"border-cyan-400/40 bg-cyan-400/10 text-cyan-300",blue:"border-blue-400/40 bg-blue-400/10 text-blue-300",green:"border-emerald-400/40 bg-emerald-400/10 text-emerald-300",violet:"border-violet-400/40 bg-violet-400/10 text-violet-300"};return <div className={`flex min-w-36 items-center gap-3 rounded-xl border p-3 shadow-xl ${colors[tone]}`}><span>{icon}</span><span><b className="block text-sm text-slate-100">{title}</b>{subtitle&&<small className="text-slate-400">{subtitle}</small>}</span></div>}
function Connector(){return <div className="h-6 w-px bg-cyan-400"/>}
function Concept({icon,concept,service,active=false}:{icon:React.ReactNode;concept:string;service:string;active?:boolean}){return <div className={`min-w-[160px] rounded-xl border p-3 ${active?"border-cyan-400/30 bg-cyan-400/5":"border-white/10 bg-white/[.03]"}`}><div className="mb-2 flex items-center gap-2 text-slate-400">{icon}<span className="text-xs">{concept}</span></div><b className="text-sm">{service}</b></div>}
