"use client";
import {useEffect,useState} from "react";
import {Cloud,Check,ChevronRight,ArrowDown,Settings2,Play,RotateCcw,BookOpen,Server,Database,Folder,Network,Shield,Activity,Layers,Trash2,Pencil,Menu,X} from "lucide-react";
import {NativeSelect,NativeSelectOption} from "../components/ui/native-select";
import {missions,services,defaults,initial,validate,costOf,applyConfig,requirements,advance,type Provider,type Config,type Session} from "./lab";

const KEY="cloud-lab-v4";
const icons:Record<string,typeof Cloud>={vm:Server,replica:Server,db:Database,storage:Folder,iam:Shield,analytics:Activity,cdn:Network,lb:Network,vpn:Network};
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="field"><span>{label}</span><NativeSelect aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><NativeSelectOption value={v} key={v}>{t}</NativeSelectOption>)}</NativeSelect></label>}
export default function Home(){
 const [provider,setProvider]=useState<Provider>("aws"),[level,setLevel]=useState("1"),[missionId,setMissionId]=useState("web");
 const [sessions,setSessions]=useState<Record<string,Session>>({}),[ready,setReady]=useState(false),[menu,setMenu]=useState(false);
 const [selected,setSelected]=useState("vm"),[draft,setDraft]=useState<Config>(defaults("vm")),[name,setName]=useState(""),[editing,setEditing]=useState(false);
 const [message,setMessage]=useState(""),[hint,setHint]=useState(false),[formError,setFormError]=useState(""),[tab,setTab]=useState("resources"),[storageWarning,setStorageWarning]=useState(false);
 const mission=missions.find(m=>m.id===missionId)||missions[0],sessionKey=provider+":"+level+":"+mission.id;
 const session=sessions[sessionKey]||initial(mission),task=mission.tasks[Math.min(session.step,mission.tasks.length-1)];
 const service=services[selected],cost=costOf(session.resources);
 const completed=missions.filter(m=>sessions[provider+":"+level+":"+m.id]?.completed).length;
 function update(next:Session){setSessions(s=>({...s,[sessionKey]:next}));}
 function clearView(){setMessage("");setHint(false);setEditing(false);setFormError("");}
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(saved.version===4&&saved.sessions&&typeof saved.sessions==="object"){
 const clean:Record<string,Session>={};for(const [key,value] of Object.entries(saved.sessions)){const s=value as Session;const id=key.split(":")[2],m=missions.find(x=>x.id===id);if(m&&Number.isInteger(s.step)&&s.step>=0&&s.step<m.tasks.length&&s.resources&&Object.entries(s.resources).every(([k,r])=>services[k]&&r&&typeof r.name==="string"&&r.config&&Object.values(r.config).every(v=>typeof v==="string"))&&Array.isArray(s.logs)&&s.logs.every(v=>typeof v==="string"))clean[key]=s;}setSessions(clean);
 if(saved.provider==="aws"||saved.provider==="gcp")setProvider(saved.provider);if(saved.level==="1"||saved.level==="2")setLevel(saved.level);if(missions.some(m=>m.id===saved.mission))setMissionId(saved.mission);
 }}}catch{setStorageWarning(true)}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify({version:4,provider,level,mission:missionId,sessions}))}catch{setStorageWarning(true)}},[ready,provider,level,missionId,sessions]);
 function openEditor(id:string){const existing=session.resources[id];setSelected(id);setName(existing?.name||mission.id+"-"+id);setDraft(existing?.config||defaults(id));setFormError("");setEditing(true);setTab("resources");}
 function save(){if(!/^[a-z][a-z0-9-]{2,39}$/.test(name)){setFormError("名前は小文字で始め、英小文字・数字・ハイフンの3〜40文字にしてください（教材共通ルール）。");return;}update(applyConfig(session,selected,name,draft));setEditing(false);setMessage("設定を保存しました。「動作テスト」で確認できます。");}
 function test(){const errors=validate(mission,session);if(errors.length){setMessage("まだ達成できていません。"+errors[0]);update({...session,passed:false,completed:false,logs:[...errors,...session.logs].slice(0,12)});}else{setMessage(task.lesson);update({...session,passed:true,completed:session.step===mission.tasks.length-1,logs:["✓ "+task.title+"：テスト成功",...session.logs].slice(0,12)});}}
 function choose(index:number){const choice=task.choices[index];const existing=session.resources[task.service];const next=applyConfig(session,task.service,existing?.name||mission.id+"-"+task.service,{...defaults(task.service),...existing?.config,...requirements(mission,session.step)[task.service],...choice.config});const errors=validate(mission,next);update({...next,passed:!errors.length,completed:!errors.length&&session.step===mission.tasks.length-1,logs:[errors.length?"テスト失敗："+errors[0]:"✓ "+task.title+"：テスト成功",...next.logs].slice(0,12)});setMessage(errors.length?choice.explanation+" "+errors[0]:task.lesson);}
 function next(){if(session.completed){const idx=missions.findIndex(m=>m.id===mission.id);setMissionId(missions[(idx+1)%missions.length].id);clearView();return;}update(advance(mission,session));clearView();}
 const regionLabel=(value:string)=>provider==="aws"?({tokyo:"ap-northeast-1 · 東京",osaka:"ap-northeast-3 · 大阪",us:"us-east-1 · 米国"}[value]||value):({tokyo:"asia-northeast1 · 東京",osaka:"asia-northeast2 · 大阪",us:"us-central1 · 米国"}[value]||value);
 return <main className={"lab "+provider+" level-"+level}>
  <header className="topbar"><div className="brand"><Cloud size={23}/><strong>Cloud Lab</strong><span className="version">v4</span></div><div className="top-controls"><Select label="クラウド" value={provider} onChange={v=>{setProvider(v as Provider);clearView()}} options={[["aws","AWS"],["gcp","Google Cloud"]]}/><Select label="レベル" value={level} onChange={v=>{setLevel(v);clearView()}} options={[["1","Lv.1 · 基礎"],["2","Lv.2 · 実践コンソール"]]}/></div><span className="simulation">学習シミュレータ · 実課金なし</span></header>
  <div className="lab-shell"><aside className={"mission-nav "+(menu?"open":"")}><div className="nav-heading"><span>ミッション</span><span>{completed} / {missions.length}</span><button className="icon-button close-nav" aria-label="ミッション一覧を閉じる" onClick={()=>setMenu(false)}><X size={20}/></button></div><nav aria-label="ミッション一覧">{missions.map((m,i)=><button key={m.id} className={mission.id===m.id?"active":""} onClick={()=>{setMissionId(m.id);clearView();setMenu(false)}}><span className="number">{sessions[provider+":"+level+":"+m.id]?.completed?<Check size={17}/>:String(i).padStart(2,"0")}</span><span>{m.title}<small>{m.category}</small></span></button>)}</nav><p className="nav-note">基礎と実践は別々に進められます。進捗はこのブラウザに保存。</p></aside>
  <section className="workspace">
   <div className="breadcrumb"><button className="mobile-missions" onClick={()=>setMenu(true)}><Menu size={17}/>ミッション変更</button><span>{provider==="aws"?"AWS learning account":"Google Cloud · learning-project"} / {mission.category}</span></div>
   <div className="mission-title"><div><p className="eyebrow">{level==="1"?"BUILD & LEARN":"PRACTICE CONSOLE"}</p><h1>{mission.title}</h1><p>{mission.summary}</p></div><button className="quiet" onClick={()=>{if(window.confirm("このミッションの構成と進捗を最初に戻しますか？")){update(initial(mission));clearView();}}}><RotateCcw size={16}/>やり直す</button></div>
   <div className="stage-strip" aria-label="課題の進捗">{mission.tasks.map((t,i)=><div key={t.title} className={session.completed||i<session.step?"finished":i===session.step?"current":""}><span>{session.completed||i<session.step?<Check size={14}/>:i+1}</span><p>{t.title}</p></div>)}</div>
   <div className="main-grid"><section className="exercise">
    <div className="task-heading"><span className="eyebrow">課題 {session.step+1} / {mission.tasks.length}</span><span>{level==="1"?"選んで試す":"設定して試す"}</span></div>
    {task.event&&<div className="event"><Activity size={18}/>{task.event}</div>}
    <h2>{task.title}</h2><p className="brief">{task.brief}</p>
    {level==="1"?<div className="choices">{task.choices.map((c,i)=><button key={c.label} disabled={session.passed} onClick={()=>choose(i)}><span className="choice-number">{String.fromCharCode(65+i)}</span><span>{c.label}</span><ChevronRight size={18}/></button>)}</div>:<><div className="console-guide"><Settings2 size={19}/><p>サービスを選択 → 設定を保存 → 動作テスト。既存リソースは「編集」で変更できます。</p></div><button className="primary test-button" disabled={editing} onClick={test}><Play size={17}/>動作テスト</button></>}
    <div aria-live="polite" className={message?"feedback "+(session.passed?"success":"info"):""}>{message&&<><strong>{session.passed?"✓ テスト成功": "テスト・操作結果"}</strong><p>{message}</p></>}</div>
    {session.passed&&<button className="primary next-button" onClick={next}>{session.completed?"次のミッションへ":"次の課題へ"}<ChevronRight size={18}/></button>}
    {session.completed&&<p className="complete-note">このミッションをクリアしました。{level==="1"?"上のレベルを切り替えると、同じ題材で設定操作を練習できます。":"設定と接続の確認まで完了しました。"}</p>}
    <button className="hint-toggle" onClick={()=>setHint(!hint)}><BookOpen size={16}/>{hint?"ヒントを閉じる":"ヒント・設定の意味"}</button>
    {hint&&<div className="hint"><p><b>使うサービス：</b>{services[task.service][provider]}</p>{Object.entries(task.require).map(([k,v])=>{const f=services[task.service].fields.find(f=>f.key===k)!;return <p key={k}><b>{f.label}：</b>{f.options.find(o=>o[0]===v)?.[1]}<small>{f.help}</small></p>})}</div>}
   </section>
   <section className="console-area">
    <div className="console-top"><div><h2>{level==="1"?"いまの構成":"リソース管理"}</h2><p>{Object.keys(session.resources).length} リソース</p></div><div className="cost"><strong>{cost.toFixed(1)}</strong><span>教材コスト / 月</span></div></div>
    <div className="topology" aria-label="構成図">{mission.path.map((id,i)=>{const Icon=icons[id]||Layers;const r=session.resources[id];return <div className="topology-item" key={id}><div className={"resource-node "+(r?"provisioned":"")}><Icon size={20}/><div><b>{services[id].title}</b><small>{r?(r.config.state==="stopped"?"停止中":r.name):"未作成"}</small></div></div>{i<mission.path.length-1&&<ArrowDown className="connection" size={18}/>}</div>})}</div><p className="diagram-note">構成要素の関係を示す模式図。通信成功は動作テストで確認します。</p>
    {level==="2"&&<><div className="resource-toolbar"><Select label="サービス" value={selected} onChange={v=>{setSelected(v);setEditing(false)}} options={Object.entries(services).map(([id,s])=>[id,s[provider]+" · "+s.title])}/><button className="primary" onClick={()=>openEditor(selected)}><span>＋</span>{session.resources[selected]?"設定を編集":"作成"}</button></div>
     {editing&&<form className="config-form" onSubmit={e=>{e.preventDefault();save()}}><div className="form-heading"><h3>{service[provider]} · {session.resources[selected]?"設定の編集":"作成"}</h3><button type="button" className="icon-button" aria-label="設定を閉じる" onClick={()=>setEditing(false)}><X size={20}/></button></div><p>{service.description}</p><label className="field"><span>{selected==="storage"?"バケット名":"リソース名"}</span><input value={name} onChange={e=>setName(e.target.value)} aria-label="リソース名" maxLength={40} required autoComplete="off"/></label><div className="config-fields">{service.fields.map(f=><div key={f.key}><Select label={f.key==="region"?(provider==="aws"?"AWSリージョン":"リージョン"):f.label} value={draft[f.key]||f.options[0][0]} onChange={v=>setDraft(d=>({...d,[f.key]:v}))} options={f.options.map(([v,label])=>[v,f.key==="region"?regionLabel(v):label])}/><small>{f.help}</small></div>)}</div><div className="form-summary"><span>保存前の教材コスト：<b>{costOf({...session.resources,[selected]:{name,config:draft}}).toFixed(1)} / 月</b></span><span>実クラウドへの作成なし</span></div>{formError&&<p role="alert" className="form-error">{formError}</p>}<div className="form-actions"><button type="button" className="quiet" onClick={()=>setEditing(false)}>キャンセル</button><button className="primary" type="submit">{session.resources[selected]?"変更を保存":"作成する"}</button></div></form>}
    </>}
    <div className="view-toggle"><button className={tab==="resources"?"active":""} onClick={()=>setTab("resources")}>リソース</button><button className={tab==="logs"?"active":""} onClick={()=>setTab("logs")}>イベントログ</button></div>
    {tab==="resources"?<div className="resource-list">{Object.entries(session.resources).length===0?<p className="empty">{level==="1"?"左の選択肢を試すと、ここに構成ができます。":"サービスを選び「作成」から始めてください。"}</p>:Object.entries(session.resources).map(([id,r])=><article key={id}><div><strong>{r.name}</strong><span>{services[id][provider]}</span><small>{services[id].fields.filter(f=>["region","count","state","access","size","tier"].includes(f.key)).map(f=>f.options.find(o=>o[0]===r.config[f.key])?.[1]).filter(Boolean).join(" / ")}</small></div>{level==="2"&&<div className="row-actions"><button onClick={()=>openEditor(id)} aria-label={r.name+"を編集"}><Pencil size={16}/>編集</button><button aria-label={r.name+"を削除"} onClick={()=>{if(window.confirm(r.name+"を削除しますか？この教材内のリソースだけが削除されます。")){const resources={...session.resources};delete resources[id];update({...session,resources,passed:false,completed:false,logs:[r.name+"を削除しました。",...session.logs].slice(0,12)});setMessage("リソースを削除しました。必要なら作成し直せます。");setEditing(false);}}}><Trash2 size={16}/></button></div>}</article>)}</div>:<div className="log-list" aria-live="polite">{session.logs.length?session.logs.map((l,i)=><p key={i}><span>{String(session.logs.length-i).padStart(2,"0")}</span>{l}</p>):<p>操作・テストの結果がここに表示されます。</p>}</div>}
   </section></div>
   <footer><p>料金・性能・通信・通知は教材用のモデルです。実コンソールの全項目やAPIを再現するものではありません。</p><details><summary>実サービスとの違い・公式ガイド</summary><p>AWSはリージョンを選んでサービスを操作、Google Cloudはプロジェクト配下で操作する流れを参考にしています。ゾーン・API有効化・証明書・細かなIAMポリシー・ネットワーク接続設定は簡略化しています。名称は用途の対応例で、同等機能を保証しません。</p><a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-instance-wizard.html" target="_blank" rel="noreferrer">AWS：インスタンス起動</a><a href="https://docs.cloud.google.com/compute/docs/instances/create-start-instance" target="_blank" rel="noreferrer">Google Cloud：VM作成</a><a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/GetStartedWithS3.html" target="_blank" rel="noreferrer">AWS：ファイル保管</a></details>{storageWarning&&<p role="status">ブラウザへの進捗保存が利用できません。この画面を閉じると進捗が失われる場合があります。</p>}</footer>
  </section></div>
 </main>
}
